### ISSUE TITLE
Where is PDF guide?

### ISSUE THREAD

**Issue by rashid-adobe** [PacktPublishing/The-Complete-Node.js-Developer-Course-3rd-Edition-#3]
You keep speaking PDF guide[https://learning.oreilly.com/videos/the-complete-node-js/9781789955071/9781789955071-video1_2/], but where is that? No link in resources section and nothing.

**Comment by Sonakshis** [comment]
Hi,
The pdf guide is present in the code bundle [Folder name: 1. Welcome]:
Download the file and unzip [video1_2.zip](https://github.com/PacktPublishing/The-Complete-Node.js-Developer-Course-3rd-Edition-/blob/master/1.%20Welcome/video1_2.zip)
Happy learning!
